Algoritmo "PrateleiraLivro"
// Disciplina   : [Lógica de Programação]
// Professor   : Hilton Elias 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/03/2026
Var
// Seção de Declarações das variáveis 

livros: vetor[0..2,0..4] de caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   livros[0,0] <- "Livro 01"
   livros[0,1] <- "Livro 02"
   livros[0,2] <- "Livro 03"
   livros[0,3] <- "Livro 04"
   livros[0,4] <- "Livro 05"

   livros[1,0] <- "Livro 06"
   livros[1,1] <- "Livro 07"
   livros[1,2] <- "Livro 08"
   livros[1,3] <- "Livro 09"
   livros[1,4] <- "Livro 10"

   livros[2,0] <- "Livro 11"
   livros[2,1] <- "Livro 12"
   livros[2,2] <- "Livro 13"
   livros[2,3] <- "Livro 14"
   livros[2,4] <- "Livro 15"

   escreval(livros[1,2])

Fimalgoritmo